### ISSUE TITLE
Our Slack channel is receiving your Travis notifications

### ISSUE THREAD

**Issue by davidrajones** [shouldsee/github_graph#1]
Hi there,

IT seems our cancerIT Slack is receiving your Travis notifications for this project. 
The problem is in this line: 

https://github.com/shouldsee/github_graph/blob/fb87ae9fc13313e38afa4f1a4ae93d908277faa6/.travis.yml#L2

I assume it's as simple as you've used one of our travis.yml files as a starting block? You can send alerts on Travis builds to your own slack channel by editing the above line and using the below.

https://slack.com/apps/A0F81FP4N-travis-ci
https://docs.travis-ci.com/user/notifications/

**Comment by shouldsee** [comment]
Ahh sorry david you are right I did not check the travis file carefully.. Removed in 330aef5
